"""
Shared, read-only access to the TEC code repos for the KB's code-facing scripts:

  scripts/check-drift.py        — checks KB facts against the code (weekly, drift.yml)
  scripts/generate-code-docs.py — writes the generated tables in C-11 (repository map)
                                  and C-44 (environment variables) from the code

Both read the repos the same way, through this module, so a table the generator writes
is exactly what the drift check will later compare against.
"""
import json
import os
import re
import subprocess

# ── repo access (read at a git ref, never the working tree — a checkout on another branch
#    must not make main look drifted) ─────────────────────────────────────────────────────

class Repo:
    def __init__(self, name, path, ref):
        self.name, self.path, self.ref = name, path, ref

    def _git(self, *args):
        r = subprocess.run(['git', '-C', self.path, *args], capture_output=True, text=True)
        return r.stdout if r.returncode == 0 else None

    def read(self, rel):
        return self._git('show', f'{self.ref}:{rel}')

    def files(self, *pathspecs):
        out = self._git('ls-tree', '-r', '--name-only', self.ref, '--', *pathspecs)
        return out.split('\n') if out else []

    def grep(self, pattern, *pathspecs):
        """[(file, line_text)] for an extended regex, source files only (tests excluded)."""
        specs = list(pathspecs) or ['.']
        specs += [':!*.test.ts', ':!*.test.tsx', ':!*.spec.ts', ':!**/__tests__/**', ':!**/node_modules/**']
        out = self._git('grep', '-I', '-E', pattern, self.ref, '--', *specs)
        hits = []
        for line in (out or '').splitlines():
            # "<ref>:<file>:<text>"
            rest = line[len(self.ref) + 1:]
            f, _, text = rest.partition(':')
            hits.append((f, text))
        return hits


def open_repos(repos_dir, ref):
    by_lower = {}
    if os.path.isdir(repos_dir):
        for d in os.listdir(repos_dir):
            if os.path.isdir(os.path.join(repos_dir, d, '.git')):
                by_lower[d.lower()] = d

    def get(name):
        d = by_lower.get(name.lower())
        if not d:
            return None
        repo = Repo(name, os.path.join(repos_dir, d), ref)
        if repo._git('rev-parse', '--verify', '--quiet', ref) is None:
            return None
        return repo
    return get



SERVICES = ['api-gateway', 'auth', 'wallet', 'payment', 'asset', 'identity',
            'notification', 'storage', 'kyc', 'commerce', 'realtime', 'analytics']
def service_dir(svc):
    return 'tec-api-gateway' if svc == 'api-gateway' else f'tec-{svc}-service'


def code_ports(backend):
    ports = {}
    for svc in SERVICES:
        d = service_dir(svc)
        main = backend.read(f'{d}/src/main.ts') or ''
        m = re.search(r"process\.env\.PORT\s*(?:\?\?|\|\|)\s*['\"]?(\d{4})", main)
        if m:
            ports[svc] = (int(m.group(1)), 'main.ts')
            continue
        # no code default (payment: PORT is required by its env schema) → the documented default
        env = backend.read(f'{d}/.env.example') or ''
        m = re.search(r'^PORT=(\d{4})', env, re.M)
        if m:
            ports[svc] = (int(m.group(1)), '.env.example — no code default')
    return ports




# ── generated blocks in KB docs ──────────────────────────────────────────────────────────

GEN_BEGIN = '<!-- BEGIN GENERATED by scripts/generate-code-docs.py — edit the code or the script, not this block -->'
GEN_END = '<!-- END GENERATED -->'


def extract_block(text):
    a, b = text.find(GEN_BEGIN), text.find(GEN_END)
    if a < 0 or b < a:
        return None
    return text[a + len(GEN_BEGIN):b].strip('\n')


def splice_block(text, block):
    a, b = text.find(GEN_BEGIN), text.find(GEN_END)
    if a < 0 or b < a:
        raise ValueError('generated-block markers not found')
    return text[:a + len(GEN_BEGIN)] + '\n' + block.strip('\n') + '\n' + text[b:]


class MissingRepo(Exception):
    pass


def need(get, name):
    repo = get(name)
    if not repo:
        raise MissingRepo(name)
    return repo


def app_root(repo):
    """The Hub keeps its Next app under tec-frontend/; every other app is at the root."""
    return 'tec-frontend/' if repo.read('tec-frontend/package.json') else ''


def package_json(repo, path='package.json'):
    raw = repo.read(path)
    return json.loads(raw) if raw else {}


def dep(pkg, name):
    return {**pkg.get('devDependencies', {}), **pkg.get('dependencies', {})}.get(name, '—')


# ── C-11: repository map ─────────────────────────────────────────────────────────────────

def render_c11(get, fleet):
    out = ['### Apps (Vercel)', '',
           'From `architecture/app-fleet.yaml` (domain, status) and each repo\'s `package.json` on `main`.',
           '',
           '| App | Repo | Domain | next | tec-ui | tec-auth | tec-sdk | Status |',
           '|---|---|---|---|---|---|---|---|']
    for a in fleet['apps']:
        repo = need(get, a['repo'])
        root = app_root(repo)
        pkg = package_json(repo, root + 'package.json')
        where = f"`{a['repo']}`" + (f" (`{root.rstrip('/')}/`)" if root else '')
        out.append(f"| {a['app']} | {where} | `{a['domain']}` | {dep(pkg, 'next')} | "
                   f"{dep(pkg, '@yasser172/tec-ui')} | {dep(pkg, '@yasser172/tec-auth')} | "
                   f"{dep(pkg, '@yasser172/tec-sdk')} | {a['status']} |")

    out += ['', '### Packages and shared repos', '',
            '| Repo | Package | Version on `main` | Role |', '|---|---|---|---|']
    for p in fleet['packages']:
        repo = need(get, p['repo'])
        if p['repo'] == 'Tec-core-backend':
            pkg = package_json(repo, 'shared/package.json')
            role = 'backend monorepo (services below) + `shared/`'
        else:
            pkg = package_json(repo)
            role = p['role']
        out.append(f"| `{p['repo']}` | `{pkg.get('name', '—')}` | {pkg.get('version', '—')} | {role} |")

    backend = need(get, 'Tec-core-backend')
    ports = code_ports(backend)
    out += ['', '### Backend services (`Tec-core-backend`, Railway)', '',
            'Port = the `main.ts` default (payment has none: its env schema requires `PORT`; the',
            'value shown is its `.env.example`). Public vs private: C-20.', '',
            '| Service | Port | Framework | Prisma schema |', '|---|---|---|---|']
    for svc in SERVICES:
        d = service_dir(svc)
        pkg = package_json(backend, f'{d}/package.json')
        deps = {**pkg.get('devDependencies', {}), **pkg.get('dependencies', {})}
        fw = ('NestJS' if '@nestjs/core' in deps else 'Express' if 'express' in deps else '—')
        if fw == 'NestJS' and '@nestjs/platform-fastify' in deps:
            fw = 'NestJS + Fastify'
        prisma = 'yes' if backend.read(f'{d}/prisma/schema.prisma') else '—'
        port = f":{ports[svc][0]}" if svc in ports else '—'
        out.append(f'| `{d}` | {port} | {fw} | {prisma} |')
    return '\n'.join(out)


# ── C-44: environment variables ──────────────────────────────────────────────────────────

ENV_DOT = re.compile(r'process\.env\.([A-Z][A-Z0-9_]*)')
ENV_IDX = re.compile(r"process\.env\[\s*['\"]([A-Z][A-Z0-9_]*)['\"]\s*\]")
ENV_TPL = re.compile(r'process\.env\[\s*`([^`]+)`\s*\]')
ENV_DESTRUCT = re.compile(r'\{([^{}]*)\}\s*=\s*process\.env\b')
ENV_VAR_FIELD = re.compile(r"envVar\s*:\s*['\"]([A-Z][A-Z0-9_]*)['\"]")
# NestJS: this.configService.get<string>('X') / config.getOrThrow('X') — how the auth service
# reads JWT_REFRESH_SECRET; missing this pattern once made a used secret look unused.
CONFIG_GET = re.compile(r"[cC]onfig\w*\.(?:get|getOrThrow)(?:<[^>]*>)?\(\s*['\"]([A-Z][A-Z0-9_]*)['\"]")
ZOD_KEY = re.compile(r'^\s*([A-Z][A-Z0-9_]+)\s*:\s*z\.', re.M)
PRISMA_ENV = re.compile(r'env\(\s*"([A-Z][A-Z0-9_]*)"\s*\)')
# Filtered here rather than with git pathspec exclusions: `:!__tests__` parses as pathspec
# magic and aborts the whole grep, and `**/x` does not match a root-level x. A silent empty
# result is the worst failure a generator can have, so the rule lives in plain Python.
_SKIP_DIRS = {'__tests__', 'e2e', 'scripts', 'node_modules'}
_SKIP_FILE = re.compile(r'\.(test|spec)\.|^(playwright|vitest|jest)\.config\.')


def is_source(path):
    parts = path.split('/')
    return not (_SKIP_DIRS & set(parts[:-1])) and not _SKIP_FILE.search(parts[-1])


def env_names(repo, base='', prisma=()):
    """(names, dynamic_patterns) read from source under `base` — tests, e2e and scripts
    excluded — plus the env("…") reads in the given Prisma schemas."""
    out = repo._git('grep', '-l', '-I', '-E', r'process\.env|envVar\s*:|[cC]onfig\w*\.get', repo.ref, '--', base or '.')
    if out is None:
        raise RuntimeError(f'git grep failed in {repo.name} under {base or "."}')
    files = [f for f in (l[len(repo.ref) + 1:] for l in out.splitlines()) if is_source(f)]
    files += [f for f in repo.files(base or '.') if f.endswith('config/env.ts') and f not in files]
    names, dynamic = set(), set()
    for f in files:
        if not re.search(r'\.(ts|tsx|js|mjs|cjs)$', f):
            continue
        text = repo.read(f) or ''
        names |= (set(ENV_DOT.findall(text)) | set(ENV_IDX.findall(text)) | set(ENV_VAR_FIELD.findall(text))
                  | set(CONFIG_GET.findall(text)))
        for group in ENV_DESTRUCT.findall(text):
            names |= {n.split(':')[0].strip() for n in group.split(',') if re.fullmatch(r'\s*[A-Z][A-Z0-9_]*\s*(:.*)?', n)}
        for tpl in ENV_TPL.findall(text):
            dynamic.add(re.sub(r'\$\{[^}]*\}', '<…>', tpl))
        if f.endswith('config/env.ts'):
            names |= set(ZOD_KEY.findall(text))
    for schema in prisma:
        names |= set(PRISMA_ENV.findall(repo.read(schema) or ''))
    return names, dynamic


def _who(users, universe, noun):
    if not users:
        return '—'
    if len(users) == len(universe):
        return f'all {len(universe)}'
    if len(users) >= len(universe) * 2 // 3:
        return f'{len(users)} — not ' + ', '.join(sorted(set(universe) - set(users)))
    return ', '.join(sorted(users))


def render_c44(get, fleet):
    apps = [a for a in fleet['apps']]
    hub = next(a for a in apps if a['app'] == 'Hub')
    domain_apps = [a for a in apps if a is not hub]
    per_app, dynamic = {}, {}
    for a in apps:
        repo = need(get, a['repo'])
        names, dyn = env_names(repo, app_root(repo).rstrip('/'),
                               [f for f in repo.files() if f.endswith('.prisma')])
        per_app[a['app']] = names
        for d in dyn:
            dynamic.setdefault(d, set()).add(a['app'])

    backend = need(get, 'Tec-core-backend')
    per_svc = {}
    for svc in SERVICES:
        d = service_dir(svc)
        names, dyn = env_names(backend, f'{d}/src', [f for f in backend.files(d) if f.endswith('.prisma')])
        per_svc[svc] = names
        for d in dyn:
            dynamic.setdefault(d, set()).add(service_dir(svc))

    per_pkg = {}
    for p in fleet['packages']:
        if p['repo'] in ('Tec-core-backend', 'tec-template-base'):
            continue
        names, _ = env_names(need(get, p['repo']), 'src')
        per_pkg[p['name']] = names

    domain_names = [a['app'] for a in domain_apps]
    fe_vars = sorted(set().union(*per_app.values()))
    out = ['### Frontend apps (Vercel)', '',
           f'Every `process.env.*` read in each app\'s source on `main` (tests, e2e, scripts and test',
           'configs excluded), plus `env("…")` in a Prisma schema.',
           '`NEXT_PUBLIC_*` is inlined into the browser bundle at BUILD time: never a secret, never an',
           'internal URL, and a change needs a redeploy. `NODE_ENV` / `VERCEL_*` / `NEXT_RUNTIME` are',
           'set by the platform.', '',
           f'| Variable | Hub | Domain apps (of {len(domain_names)}) |', '|---|---|---|']
    for v in fe_vars:
        users = [n for n in domain_names if v in per_app[n]]
        out.append(f"| `{v}` | {'✓' if v in per_app['Hub'] else '—'} | {_who(users, domain_names, 'apps')} |")

    svc_names = [service_dir(s).replace('tec-', '').replace('-service', '') for s in SERVICES]
    be_vars = sorted(set().union(*per_svc.values()))
    out += ['', '### Backend services (Railway)', '',
            'Every `process.env.*` and NestJS `configService.get(\'…\')` read under each service\'s `src/`,',
            'plus the keys of its zod schema in `src/config/env.ts` where it has one, the gateway\'s',
            '`envVar` service-registry entries, and `env("…")` in its Prisma schema.',
            'Railway sets `PORT` per service.', '',
            f'| Variable | Services (of {len(SERVICES)}) |', '|---|---|']
    for v in be_vars:
        users = [n for s, n in zip(SERVICES, svc_names) if v in per_svc[s]]
        out.append(f'| `{v}` | {_who(users, svc_names, "services")} |')

    out += ['', '### Packages', '', '| Package | Variables read |', '|---|---|']
    for name, names in per_pkg.items():
        out.append(f"| `{name}` | {', '.join(f'`{n}`' for n in sorted(names)) or '—'} |")

    out += ['', '### Names built at run time', '',
            'Read with a computed name, so they cannot appear in the tables above.', '',
            '| Pattern | Where |', '|---|---|']
    for d in sorted(dynamic):
        out.append(f"| `{d}` | {', '.join(sorted(dynamic[d]))} |")
    return '\n'.join(out)
